### ISSUE TITLE
Incorrect bitmap# in isDecomposable

### ISSUE THREAD

**Issue by adithyaov** [composewell/unicode-transforms#43]
`isDecomposable` from `Data.Unicode.Properties.Decomposable` returns `False` for Hangul characters.

**Comment by Bodigrim** [comment]
I believe this is intentional: `isDecomposable` serves as a mask for `decomposeChar`. The latter does not include Hangul characters, because they are decomposed algorithmically. 

However, it may be reasonable to change its name to `isDecomposableAndNotHangul` or whatever.

**Comment by harendra-kumar** [comment]
Even if we mark them decomposable it should do no harm. We should never be calling isDecomposable/decomposeChar on them in the normalization code. In fact marking the range decomposable will act as a cross check for that, if we are calling isDecomposable and then decomposeChar for those then it will fail.

It may be useful if we want to check the char property whether it is decomposable or not. But yes it won't act as a mask for decomposeChar any more. Which should be ok, I guess.

**Comment by adithyaov** [comment]
This issue no longer concerns this repository. The documentation of `isDecomposable` in `unicode-data` is very clear.
