### ISSUE TITLE
Unable to build with ghc 9

### ISSUE THREAD

**Issue by jgm** [composewell/unicode-transforms#59]
because of the upper bound on ghc-prim: can it be relaxed?

```
[__0] trying: unicode-collation-0.1 (user goal)
[__1] trying: unicode-transforms-0.3.7.1 (dependency of unicode-collation)
[__2] next goal: base (dependency of unicode-collation)
[__2] rejecting: base-4.15.0.0/installed-4.15.0.0 (conflict:
unicode-transforms => ghc-prim>=0.2 && <0.7, base =>
ghc-prim==0.7.0/installed-0.7.0)
```

**Comment by jgm** [comment]
Note: using `--allow-newer`, my build succeeded and all tests passed.
So, that is some confirmation that relaxing the bound would be harmless.

**Comment by harendra-kumar** [comment]
Thanks @jgm .

Yes, the upper bound of ghc-prim can be relaxed. Let's fix this quickly to enable dependent packages to move to ghc-9.

BTW `text` performance on GHC 9.0 is broken https://gitlab.haskell.org/ghc/ghc/-/issues/19557 .

**Comment by adithyaov** [comment]
@Bodigrim, This fix requires only bumping versions of a few
dependencies. Do you recommend releasing a new version with the
updated bounds or creating a new revesion on hackage.

**Comment by Bodigrim** [comment]
I suggest making a revision.

**Comment by adithyaov** [comment]
@jgm A new revision has been made for `v0.3.7.1`. The library and tests should compile with ghc 9.

**Comment by jgm** [comment]
Great, thanks!

**Comment by adithyaov** [comment]
@jgm I'm closing this. Please feel free to reopen it if there are any problems.
