### ISSUE TITLE
Replace gauge with tasty-bench

### ISSUE THREAD

**Issue by adithyaov** [composewell/unicode-transforms#61]

**Comment by adithyaov** [comment]
@Bodigrim Does tasty have replacements for `Gauge.Main.Options`?
Is there a way to mimic this behavior?

@harendra-kumar Can we simplify the benchmarks and remove parsing CLI args? Where do we use them?

**Comment by Bodigrim** [comment]
@adithyaov See https://github.com/Bodigrim/tasty-bench#custom-command-line-options

**Comment by harendra-kumar** [comment]
@adithyaov - @rnjtranjan did this in streamly benchmarks, you can refer to that as well.
