### ISSUE TITLE
Status of GHC 7.8 support

### ISSUE THREAD

**Issue by Bodigrim** [composewell/unicode-transforms#68]
https://github.com/composewell/unicode-transforms/blob/cd6040cc70152b43c48aede54d1ebb93860ad156/unicode-transforms.cabal#L17-L19
suggests that the earliest supported GHC is 7.10, but on the other hand 
https://github.com/composewell/unicode-transforms/blob/cd6040cc70152b43c48aede54d1ebb93860ad156/unicode-transforms.cabal#L78-L79
means that GHC 7.8 is also allowed. This causes build failures at https://matrix.hackage.haskell.org/#/package/unicode-transforms

I think it's totally fine to drop support of GHC 7.8, just need to reflect it by requiring `base >= 4.8`.

**Comment by harendra-kumar** [comment]
Yes, we should bump the lower bound on base.
