### ISSUE TITLE
GHC 9.2.1 support

### ISSUE THREAD

**Issue by DrewFenwick** [composewell/unicode-transforms#72]
The `ghc-prim` and `text` bounds need to be bumped to build on GHC 9.2.1

The test suite however is help up by generics-sop via getopts-generics, see:
- well-typed/generics-sop#145
- well-typed/generics-sop#147
- soenkehahn/getopt-generics#65

**Comment by adithyaov** [comment]
Thank you for opening the issue and getting this to our notice. 
I will get `unicode-transforms` working with GHC 9.2.1 once the mentioned issues are resolved.

If the need is urgent and you have any suggestions for the time being, please let me know.

**Comment by harendra-kumar** [comment]
`getopt-generics` is not even being used in unicode-transforms, it is a spurious dependency. It was used earlier but at some point the code was removed and it became redundant.

**Comment by adithyaov** [comment]
The dependency has been removed in master. GHC 9.2.1 is supported now.
